# 异常处理

```go
type error interface{
    Error() string
}
```



**error: 错误信息，错误不是很致命**

```go
package main

import "errors"

func div(a, b int) (res int, err error) {
	err = nil
	if b == 0 {
		err = errors.New("b must not be 0")
	} else {
		result = a + b
	}
	return
}

func main() {
	result, err := div(10, 0)
	if err != nil {
		// do
	}
}

```



**panic: 程序错误非常致命， 除0**

```go
package main
import "fmt"

func main(){
    fmt.Println("hello")
    
    // 导致程序崩溃
    panic("some information")
    fmt.Println("world")
}
```



**recover: 在 defer 中使用**

```go
package main
import "fmt"

func test(x int){
    // 出错了， 不要 panic，恢复一下继续跑！！
    defer func(){
        if err:=recover(); err!=nil{
            fmt.Println(err)
        }
    }()
    var a [10]int
    a[x] = 111
}

```

